plugins {
    id 'groovy'
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'com.gradle.plugin-publish' version '0.11.0'
}

group 'de.dfki.mary'
version '5.5-SNAPSHOT'
description 'A replacement for the legacy VoiceImportTools in MaryTTS'

sourceCompatibility = '1.8'

gradlePlugin {
    website = 'http://mary.dfki.de'
    vcsUrl = 'https://github.com/marytts/gradle-marytts-voicebuilding-plugin'
    plugins {
        base {
            id = 'de.dfki.mary.voicebuilding-base'
            implementationClass = 'de.dfki.mary.voicebuilding.VoicebuildingBasePlugin'
            displayName = 'Voicebuilding Base Plugin'
            description = project.description
            tags.set(['TTS', 'speech synthesis', 'voicebuilding'])
        }
        data {
            id = 'de.dfki.mary.voicebuilding-data'
            implementationClass = 'de.dfki.mary.voicebuilding.VoicebuildingDataPlugin'
            displayName = 'Voicebuilding Data Plugin'
            description = project.description
            tags.set(['TTS', 'speech synthesis', 'voicebuilding'])
        }
        festvox {
            id = 'de.dfki.mary.voicebuilding-festvox'
            implementationClass = 'de.dfki.mary.voicebuilding.VoicebuildingFestvoxPlugin'
            displayName = 'Voicebuilding FestVox Plugin'
            description = project.description
            tags.set(['TTS', 'speech synthesis', 'voicebuilding'])
        }
        legacy {
            id = 'de.dfki.mary.voicebuilding-legacy'
            implementationClass = 'de.dfki.mary.voicebuilding.VoicebuildingLegacyPlugin'
            displayName = 'Voicebuilding Legacy Plugin'
            description = project.description
            tags.set(['TTS', 'speech synthesis', 'voicebuilding'])
        }
    }
}

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            gradlePluginPortal()
        }
        filter {
            includeModule 'de.dfki.mary', 'gradle-marytts-component-plugin'
            includeModule 'io.github.m2ci-msp', 'gradle-praat-wrapper-plugin'
        }
    }
}

dependencies {
    implementation localGroovy()
    implementation group: 'de.dfki.mary', name: 'marytts-runtime', version: libs.versions.marytts.get(), {
        exclude group: '*', module: 'groovy-all'
        exclude group: 'com.twmacinta', module: 'fast-md5'
        exclude group: 'gov.nist.math', module: 'Jampack'
    }
    implementation group: 'de.dfki.mary', name: 'gradle-marytts-component-plugin', version: '0.3.3'
    implementation group: 'io.github.m2ci-msp', name: 'gradle-praat-wrapper-plugin', version: '0.8.0'
    implementation group: 'io.github.m2ci-msp', name: 'jtgt', version: '0.7.1'
    testImplementation group: 'org.testng', name: 'testng', version: '7.5.1'
    testImplementation group: 'xmlunit', name: 'xmlunit', version: '1.6'
    constraints {
        implementation('de.dfki.lt.jtok:jtok-core:1.9.4') {
            because 'transitive dependency v1.9.3 is not available in Maven Central'
        }
    }
}

java {
    withSourcesJar()
}

processResources {
    doLast {
        file("$destinationDir/maryttsVersion.txt").text = libs.versions.marytts.get()
    }
}

test {
    useTestNG {
        parallel = 'classes'
    }
    testLogging {
        events 'started', 'passed', 'failed', 'skipped'
        exceptionFormat = 'full'
        info {
            showStandardStreams = true
        }
    }
    failFast = true
    systemProperty 'java.io.tmpdir', temporaryDir
    systemProperty 'maryVersion', libs.versions.marytts.get()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url version.endsWith('-SNAPSHOT') ? 'https://oss.jfrog.org/artifactory/oss-snapshot-local' : 'https://api.bintray.com/maven/marytts/marytts/gradle-marytts-voicebuilding-plugin'
            credentials {
                username = findProperty('bintrayUser')
                password = findProperty('bintrayApiKey')
            }
        }
    }
}
